name: Testing_Actions

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-24.04
    env:
      node-version: "22.x"
      dotnet-version: "10.x"
      python-version: "3.13"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      # Create a 100-line test file
      - name: Create test artifact file
        run: echo "Hello My NAme is Mayur Ashok Labhsajycgy yugfihfgsj ghsfhoihh hbsuvibvhjbhu ylisgifdhbiv" > output.txt

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact-upload
          path: output.txt
          retention-days: 100

  Download:
    runs-on: ubuntu-24.04
    needs: setup
    steps:
      - name: donload artifact
        uses: actions/download-artifact@v4
        with:
          name: test-artifact-upload
          path: /mayur
    
      - name: check file
        run: cat /mayur/output.txt
  
  
          
