name: Main CI Pipeline

on:
  push:
    branches: [main ]
  
jobs:
  call-reusable-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      Name: 'Mayur Ashok Labhade'
      Age: '28'
    secrets:
      REPO_NAME: ${{ secrets.REPO_NAME}}
