name: Reusable Workflow

on:
  workflow_call:
    inputs:
      Name:
        description: "User-Name"
        type: string
        required: true
      Age:
        description: "Your-Age"
        required: true
        type: string
    secrets:
      REPO_NAME:
        required: false
jobs:
  print:
    runs-on: ubuntu-24.04
    steps:
      - name: printing name
        run: echo "${{ inputs.Name}}"
      - name: printing Age
        run: echo "${{inputs.Age}}"


