name: Reusable Workflow

on:
  workflow_call:
    inputs:
      Name:
        description: "User-Name"
        type: string
        required: true
      Age:
        description: "Your-Age"
        required: true
        type: string
    secrets:
      REPO_NAME:
        required: false
jobs:


