name: Testing
on:
  push:
    branches: [main]
env:
  Workflow_Level: Workflow
jobs:
  Scan:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        continue-on-error: true
      - name: FailureTest
        if: failure()
        run: print ("Hello From Python")
        shell: python
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"
  Build:
    runs-on: ubuntu-24.04
    needs: Scan
    env:
      Job_Level: Job
    steps:
      - name: Checking Env
        env:
          Step_Level: Step
        run: |
          echo "$Workflow_Level"
          echo "$Job_Level"
          echo "${{env.Step_Level}}"
      - name: Dyna-En-vari
        run: echo "Dyn_name=MayurAshokLabhade" >> $GITHUB_ENV
      - run: echo "Name is ${{env.Dyn_name}}"
      
  Out:
    runs-on: ubuntu-24.04
    outputs:
      Mayur: ${{steps.w1.outputs.out-name}}
    steps:
      - name: stps-otputs
        id: w1
        run: echo "out-name=Sakshi" >> $GITHUB_OUTPUT

  Use:
      runs-on: ubuntu-24.04
      needs:
        - Out
      steps:
        - run: echo " ${{needs.Out.outputs.Mayur}}"
          
  Secrets:
    runs-on: ubuntu-latest
    environment: dev
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo " Repo Name is  ${{ secrets.REPO_NAME }}"
      - run: echo " Environmnet secrets is ${{ secrets.ENVREPO}}"
      - run: echo " cat $GITHUB_TOKEN "
