name: Testing
on:
  push:
    branches: [main]
env:
  Workflow_Level: Workflow
jobs:
  Scan:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello From Bash Shell"
      - run: print ("Hello From Python")
        shell: python
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"
  Build:
    runs-on: ubuntu-24.04
    needs: Scan
    env:
      Job_Level: Job
    steps:
      - name: Checking Env
        env:
          Step_Level: Step
        run: |
          echo "$Workflow_Level"
          echo "$Job_Level"
          echo "${{env.Step_Level}}"
          
